Feature: User relationship scenarios

  Background:
	Given a running shotgun viewserver
	Given a client named "client1" connected to "{client1.url}"
	Given a client named "client2" connected to "{client2.url}"
	Given a client named "client3" connected to "{client3.url}"
	Given a client named "client4" connected to "{client4.url}"
	Given "client1" All data sources are built
	Given "client1" controller "driverController" action "registerDriver" invoked with data file "allRounder.json"
	Given "client2" controller "driverController" action "registerDriver" invoked with data file "brickLayerRegistration.json"
	Given "client3" controller "driverController" action "registerDriver" invoked with data file "plastererRegistration.json"
	Given "client4" controller "driverController" action "registerDriver" invoked with data file "groundWorkerRegistration.json"


  Scenario: Newly registered users can see themselves
	Given "client2" dimension filters
	  | Name             | Type   | Value   |
	  | dimension_userId | String | @userId |
	When "client2" subscribed to report "userReport"
	Then "client2" the following data is received eventually
	  | ~TEId | contactNo    | distance | email                        | firstName | id | imageUrl | initiatedByMe | lastName   | latitude | longitude | market | notional | online | range | rank | ratingAvg | relationshipStatus | selectedContentTypes                        | statusMessage | type   | userId                                           | ~Action     | ~ColumnType  | ~Name                 |
	  | 1     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | SchemaReset |              |                       |
	  | 2     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | dimension_userId      |
	  | 3     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | userId                |
	  | 4     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Long         | created               |
	  | 5     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Long         | dob                   |
	  | 6     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Long         | lastModified          |
	  | 7     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | firstName             |
	  | 8     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | lastName              |
	  | 9     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | contactNo             |
	  | 10    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | selectedContentTypes  |
	  | 11    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | email                 |
	  | 12    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | type                  |
	  | 13    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | stripeDefaultSourceId |
	  | 14    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | fcmToken              |
	  | 15    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | chargePercentage      |
	  | 16    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | latitude              |
	  | 17    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | longitude             |
	  | 18    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | range                 |
	  | 19    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | imageUrl              |
	  | 20    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | NullableBool | online                |
	  | 21    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | userStatus            |
	  | 22    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | statusMessage         |
	  | 25    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | ratingGroupBy_userId  |
	  | 26    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | count                 |
	  | 27    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | ratingAvg             |
	  | 28    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | rank                  |
	  | 29    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | DataReset   |              |                       |
	  | 30    | 447966265016 |          | modestasbricklayer@gmail.com | Modestas  |    |          |               | BrickLayer | 0.0      | 0.0       |        |          | True   | 50    | 0    | 0.0       |                    | {"5":{"selectedProductIds":["BrickLayer"]}} |               | driver | {client2_driverController_registerDriver_result} | RowAdd      |              |                       |

  Scenario: Newly registered users can be seen by each other

  Scenario: Can see driver for product in userProduct report
	Given "client1" report parameters
	  | Name           | Type    | Value |
	  | showOutOfRange | String  | false |
	  | showUnrelated  | String  | true  |
	  | latitude       | Integer | 0     |
	  | longitude      | Integer | 0     |
	  | userId         | Integer | 0     |
	  | maxDistance    | Integer | 0     |
	Given "client1" dimension filters
	  | Name                | Type   | Value      |
	  | dimension_productId | String | BrickLayer |
	And "client1" paging from 0 to 100 by "userId" descending
	When "client1" subscribed to report "usersForProductAll"
	Then "client1" the following data is received eventually
	  | ~TEId | contactNo    | distance | email                        | firstName | id | imageUrl | initiatedByMe | lastName   | latitude | longitude | market | notional | online | range | rank | ratingAvg | relationshipStatus | selectedContentTypes                        | statusMessage | type   | userId                                           | ~Action     | ~ColumnType  | ~Name                |
	  | 1     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | SchemaReset |              |                      |
	  | 2     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | relationshipStatus   |
	  | 3     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | NullableBool | initiatedByMe        |
	  | 4     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | userId               |
	  | 5     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | firstName            |
	  | 6     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | lastName             |
	  | 7     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | contactNo            |
	  | 8     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | selectedContentTypes |
	  | 9     |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | email                |
	  | 10    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | type                 |
	  | 11    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | latitude             |
	  | 12    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | longitude            |
	  | 13    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | range                |
	  | 14    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | imageUrl             |
	  | 15    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Bool         | online               |
	  | 16    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | String       | statusMessage        |
	  | 17    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | ratingAvg            |
	  | 18    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Double       | distance             |
	  | 19    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | ColumnAdd   | Int          | rank                 |
	  | 20    |              |          |                              |           |    |          |               |            |          |           |        |          |        |       |      |           |                    |                                             |               |        |                                                  | DataReset   |              |                      |
	  | 21    | 447966265016 | 0.0      | modestasbricklayer@gmail.com | Modestas  |    |          | Null          | BrickLayer | 0.0      | 0.0       |        |          | true   | 50    | 0    | 0.0       |                    | {"5":{"selectedProductIds":["BrickLayer"]}} |               | driver | {client2_driverController_registerDriver_result} | RowAdd      |              |                      |