

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_DELIVERY = 'UPDATE_DELIVERY';
