# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShotgunClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShotgunClient
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'HockeySDK', '~> 5.1.2'

  target 'ShotgunClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ShotgunClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShotgunClient-tvOS

  target 'ShotgunClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
